### ISSUE TITLE
Recruit UI/UX designers to help with gathering feedback and initial design prototyping

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/UniTT#11]

**Comment by richpomfret** [comment]
@DeniseColbert have we had a chance to spread the word yet for any suitable volunteers?

**Comment by DeniseColbert** [comment]
Ads are up on Reach Volunteering and Social Coder, and Work in Startups.

**Comment by PatReynolds** [comment]
A number of people have expressed interest.  Denise and Pat have put together a document to see what their skills are, and will take forwards.

**Comment by DeniseColbert** [comment]
Closing
