### ISSUE TITLE
Create WebBMD project spec

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/UniTT#14]
To prepare project for WebBMD (to replace MacBMD and provide browser based alternative for WinBMD). 

Part of this task will be collating information for WinBMD and to specify key requirements/features and functions.

**Comment by PatReynolds** [comment]
Transferring from Coordination to UniTT as part of the milestone cleanup process.  Maybe already covered here.

**Comment by richpomfret** [comment]
We can close this - will be a part of UniTT.
