### ISSUE TITLE
New name for UniTT

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/UniTT#16]
Kirk has pointed out that "universal transcription" has an existing meaning which may need to serious confusion outside our walls.

We therefore need a name that is not "Universal transcription" but also indicates that this is a tool that can be used for a wide range of transcription projects of the "spreadsheet" kind (e.g. not the transcriptions of last wills and testaments, which while they might be indexed using the took, would not be transcribed in full.

**Comment by PatReynolds** [comment]
An element that means "not just for one type of record"
adaptable, adjustable, alterable,  common, communal, changeable, elastic, flexible, general-purpose, mixed-use, multipurpose, modifiable, plastic, supple, ubiquitous,  variable, versatile, wide, 

Possibly with a 'historic records element.

historic record, archival, history, entry

possibly
Online

And then "transcription tool"

Ideally an acronym is a word with meaning!

Eg common or communal + entry + transcription tool would get us ComETT

**Comment by PatReynolds** [comment]
@DeniseColbert  @AlOneill  what do you think? to the words? Anything to add?  Maybe something around community , volunteer, etc?

**Comment by richpomfret** [comment]
Discussed in our scrum - agreed to go with ComETT.

**Comment by PatReynolds** [comment]
Kirk suggests ComFETT (Community Formatted Entry Transcription Tool)

ComSETT (Community Spreadsheet Entry Transcription Tool)

**Comment by DeniseColbert** [comment]
Closing
