### ISSUE TITLE
Discussing project with BB

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/UniTT#17]
Go through questions about what software is currently 'out there' and what we might use rather than developing our own, or whether we can combine. Establish market need.

**Comment by richpomfret** [comment]
Let's trial/evaluate this for FreeREG - perhaps Steve/Eric might take a look and try it out.

**Comment by DeniseColbert** [comment]
@PatReynolds to send links from Ben to Eric/Steve to trial.
